#!/bin/bash

set -e

npm run lint

output=$(npm run type-coverage)
if echo "$output" | grep -q "lower than "; then
    echo "$output"
    exit 1  # Terminate the hook script with a non-zero exit code
else
    echo "Type coverage is good! 🎉"
fi

npm run test

npm run build