export const enum MaskExpression {
    SEPARATOR = 'separator',
    PERCENT = 'percent',
    IP = 'IP',
    CPF_CNPJ = 'CPF_CNPJ',
    MONTH = 'M',
    MINUTE = 'm',
    HOUR = 'h',
    HOURS = 'H',
    DAY = 'd',
    SECOND = 's',
    LETTER_S = 'S',
    DOT = '.',
    COMMA = ',',
    CURLY_BRACKETS_LEFT = '{',
    CURLY_BRACKETS_RIGHT = '}',
    MINUS = '-',
    OR = '||',
    HASH = '#',
}
