name: GitHub pages

on:
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install deps
              run: |
                  bun i

            - name: Semantic Release
              id: semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  npx semantic-release

            - name: Build demo app
              env:
                  RELEASE_VERSION: ${{ steps.semantic-release.outputs.new-release-version }}
              run: |
                  echo '********'
                  echo "RELEASE_VERSION: $RELEASE_VERSION"
                  echo '********'
                  bash .github/workflows/scripts/replace_template.sh $RELEASE_VERSION
                  bun run build

            - name: Deploy demo
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist/ngx-mask/browser

        outputs:
            version: ${{ steps.semantic-release.outputs.new-release-version }}

    slack_notification:
        needs:
            - build
        runs-on: ubuntu-latest
        steps:
            - name: Post to a Slack channel
              id: slack
              uses: slackapi/slack-github-action@v2.0.0
              with:
                  method: chat.postMessage
                  channel-id: 'deployments'
                  token: ${{ secrets.SLACK_BOT_TOKEN }}
                  payload: |
                      {
                        "text": "GitHub Action build result: ${{ job.status == 'success' && ':white_check_mark:' || ':x:' }}",
                        "blocks": [
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "GitHub Action build result: ${{ job.status == 'success' && ':white_check_mark:' || ':x:' }}"
                            }
                          },
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "Project: `${{ github.event.repository.name }}`"
                            }
                          },
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "Version: `${{ needs.build.outputs.version || 'TBA' }}`"
                            }
                          },
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "Commit/PR URL: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                            }
                          },
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "Website URL: ${{ secrets.WEBSITE_URL || 'TBA' }}"
                            }
                          }
                        ]
                      }
