name: GitHub pages

on:
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v6
              with:
                  submodules: true

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - uses: actions/setup-node@v6
              with:
                  node-version: 22

            - name: Install deps
              run: |
                  bun i

            - name: Semantic Release
              id: semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  npx semantic-release

            - name: Build demo app
              env:
                  RELEASE_VERSION: ${{ steps.semantic-release.outputs.new-release-version }}
              run: |
                  echo '********'
                  echo "RELEASE_VERSION: $RELEASE_VERSION"
                  echo '********'
                  bash .github/workflows/scripts/replace_template.sh $RELEASE_VERSION
                  bun run build

            - name: Deploy demo
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist/ngx-mask/browser

        outputs:
            version: ${{ steps.semantic-release.outputs.new-release-version }}
