name: build and quality

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - main
            - develop
        types: [opened, synchronize, reopened]

jobs:
    quality-check:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 0
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Check quality
              run: |
                  bun i
                  bash .github/workflows/scripts/quality.sh
