name: build and quality

on: [push]

jobs:
    quality-check:
        runs-on: ubuntu-latest
        outputs:
          version: ${{ steps.get_version.outputs.version }}
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
                  ref: ${{ env.REF }}
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Check quality
              run: |
                  bun i
                  bash .github/workflows/scripts/quality.sh

            - name: Extract version
              id: get_version
              run: |
                VERSION=$(node -p "require('./dist/ngx-mask-lib/package.json').version")
                echo "version=$VERSION" >> $GITHUB_OUTPUT

    version_check:
      needs:
        - quality-check
      runs-on: ubuntu-latest
      steps:
        - name: Display version
          run:
            echo "${{ needs.quality-check.outputs.version || 'TBA' }}"