name: build and quality

on: [push]

jobs:
    quality-check:
        runs-on: ubuntu-latest
        outputs:
          version: ${{ steps.get_version.outputs.version }}
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
                  ref: ${{ env.REF }}
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Check quality
              run: |
                  bun i
                  bash .github/workflows/scripts/quality.sh

            - name: Extract version
              id: get_version
              run: |
                VERSION=$(node -p "require('./dist/ngx-mask-lib/package.json').version")
                echo "version=$VERSION" >> $GITHUB_OUTPUT

    slack_notification:
      needs:
        - quality-check
      runs-on: ubuntu-latest
      steps:
        - name: Post to a Slack channel
          id: slack
          uses: slackapi/slack-github-action@v1.27.0
          with:
            channel-id: 'deployments'
            payload: |
              {
                "text": "GitHub Action build result: ${{ job.status == 'success' && ':white_check_mark:' || ':x:' }}",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "GitHub Action build result: ${{ job.status == 'success' && ':white_check_mark:' || ':x:' }}"
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": "Version: `${{ needs.quality-check.outputs.version || 'TBA' }}`"
                    }
                  },
                
                ]
              }
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}