name: build and quality

on: [push]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check quality
        run: |
          npm ci --legacy-peer-deps
          git submodule update --init --recursive --remote
          npm run lint
          npm run cypress:bash
          npm test
          npm run build
          npm run build:lib
        
