name: build and quality

on: [push]

env:
    snyk_token: ${{ secrets.SNYK_TOKEN }}

jobs:
  quality-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check quality
        run: |
          npm install --package-lock-only --force
          npm ci --force
          git submodule update --init --recursive --remote
          bash .github/workflows/scripts/quality.sh

