name: build and quality

on: [push]

jobs:
    quality-check:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
                  ref: ${{ env.REF }}
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Check quality
              run: |
                  bun i
                  bash .github/workflows/scripts/quality.sh
